### ISSUE TITLE
404 page text is cutted

### ISSUE THREAD

**Issue by selankon** [vocdoni/ui-scaffold#701] opened 2024-05-29 06:44 UTC
![image](https://github.com/vocdoni/ui-scaffold/assets/16777076/f63ebf97-3e4b-4dee-b2f3-a5fef6f870b4)

There are something breaking the 404 text on top

**Comment by gerouvi** [comment] 2024-06-03 06:55
<img width="719" alt="Screenshot 2024-06-03 at 08 53 07" src="https://github.com/vocdoni/ui-scaffold/assets/78085338/189a09c0-122e-4eb2-a01f-32b1016ff422">

I can't reproduce the error; for me, the 404 page not found appears fine

**Comment by selankon** [comment] 2024-06-03 07:30
Strange it happen to me only on Firefox.. https://app.vocdoni.io/dalkm

Can you reproduce it there @gerouvi ?

**Comment by elboletaire** [comment] 2024-06-03 13:45
> Strange it happen to me only on Firefox.. [app.vocdoni.io/dalkm](https://app.vocdoni.io/dalkm)
> 
> Can you reproduce it there @gerouvi ?

I see it well (checked using Firefox, Chrome and Edge)
![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/db0f1ab4-f6c3-412b-b951-74da4c053b6f)
![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/8da8a052-23a2-44dc-8953-35f67af83a1b)
![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/ea94a3e1-b000-4547-afda-403901831a3d)

Maybe one of your addons? Closing unless we find a way to properly reproduce it

**Closed by elboletaire** 2024-06-03 13:45 UTC

**Comment by gerouvi** [comment] 2024-06-03 13:49
> Strange it happen to me only on Firefox.. https://app.vocdoni.io/dalkm
> 
> Can you reproduce it there @gerouvi ?

I can't reproduce it, I usually use Firefox
