### ISSUE TITLE
Auth failure if creating additional anonymous processes with Spreadsheets and not refreshing the page in-between

### ISSUE THREAD

**Issue by emmdim** [vocdoni/ui-scaffold#438] opened 2023-11-29 18:37 UTC
Creating an anonmyous process using the example csv provided by the UI  sometimes does not allow the authentication of the users based on the data defined in the CSV.

**Comment by elboletaire** [comment] 2023-11-29 19:12
I could reproduce it with a census file I use often by adding an empty line to the end of the file.

**Comment by elboletaire** [comment] 2023-12-01 15:40
The issue is reproducible when you create (at least) two processes without refreshing the page, since there's no re-fetch of the account information after creating the process thus not updating the electionIndex used for the salt of the spreadsheet elections.

The solution should be to add a `fetchAccount` after creating the process, but doing so has arisen other issues: react-router decides to not re-render the page after changing the URL path, but this only happens with the `fetchAccount` added there.

Further testing and debugging has to be done, but since it's gonna be a rabbit hole, I'll do it after closing things in #449

**Closed** 2023-12-14 10:33 UTC
Labels: bug
